- hosts: all
  become: yes
  become_user: root
  become_method: sudo

  tasks:
    - name: ensure nginx is at the latest version
      command: amazon-linux-extras install nginx1.12
    - name: start nginx
      service:
          name: nginx
          state: started